steps:
# Terraform
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    terraform init \
    -backend-config="bucket=$PROJECT_ID-tf-state" \
    -backend-config="prefix=terraform_gcp/cloud-composer"
  dir: terraform
      
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - plan
  dir: terraform

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - apply
  - -auto-approve
  dir: terraform

# Cloud Function
- id: 'deploy Cloud Function'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  args:
  - gcloud
  - functions
  - deploy
  - pubsub_producer
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python310
  - --update-env-vars=PROJECT_ID=$PROJECT_ID
  - --ingress-settings=all
  dir: producer


options:
  env:
    - TF_VAR_project_id=$PROJECT_ID
tags:
  - terraform
  - data-analytics
  - pubsub-to-bigquery
  - plan-apply

timeout: 3600s
